Data sets we will be working with:

In [14]:
library(readxl) #function that allows us to import our excel files

In [24]:
getwd() #function to know my current working directory

[1] "/home/jovyan/DSCI_100_125"

In [46]:
infltion_data <- read_csv("/home/jovyan/DSCI_100_125/annual_inflation.csv", skip=11, col_names = c("date","annual_inflation"))
infltion_data

Rows: 33 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl  (1): annual_inflation
date (1): date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

   date       annual_inflation
1  1989-01-01 4.827003
2  1990-01-01 5.397956
3  1991-01-01 4.234964
⋮  ⋮          ⋮
31 2019-01-01 1.812210
32 2020-01-01 1.233584
33 2021-01-01 4.697859

In [47]:
real_gdp_data <- read_csv("/home/jovyan/DSCI_100_125/real_gdp.csv", skip=3, col_names = c("year","real_gdp_growth_rate","type"))
real_gdp_data

Rows: 32 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): year, type
dbl (1): real_gdp_growth_rate

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

   year real_gdp_growth_rate type
1  '90   1.9                 in %
2  '91  -0.1                 in %
3  '92   3.5                 in %
⋮  ⋮    ⋮                    ⋮
30 '19   2.3                 in %
31 '20  -3.4                 in %
32 '21   5.7                 in %

In [50]:
unemployment_data <- read_csv("/home/jovyan/DSCI_100_125/unemployment_rates.csv", skip=1)
unemployment_data

New names:
• `` -> `...9`
• `` -> `...10`
• `` -> `...11`
• `` -> `...12`
• `` -> `...13`
• `` -> `...14`
• `` -> `...15`
• `` -> `...16`
• `` -> `...17`
• `` -> `...18`
• `` -> `...19`
• `` -> `...20`
• `` -> `...21`
• `` -> `...22`
• `` -> `...23`
• `` -> `...24`
• `` -> `...25`
• `` -> `...26`
• `` -> `...27`
• `` -> `...28`
• `` -> `...29`
• `` -> `...30`
• `` -> `...31`
• `` -> `...32`
• `` -> `...33`
• `` -> `...34`
• `` -> `...35`
• `` -> `...36`
• `` -> `...37`
• `` -> `...38`
• `` -> `...39`
• `` -> `...40`
• `` -> `...41`
• `` -> `...42`
• `` -> `...43`
• `` -> `...44`
• `` -> `...45`
• `` -> `...46`
• `` -> `...47`
• `` -> `...48`
• `` -> `...49`
• `` -> `...50`
• `` -> `...51`
• `` -> `...52`
• `` -> `...53`
• `` -> `...54`
• `` -> `...55`
• `` -> `...56`
• `` -> `...57`
• `` -> `...58`
• `` -> `...59`
• `` -> `...60`
• `` -> `...61`
• `` -> `...62`
• `` -> `...63`
• `` -> `...64`
• `` -> `...65`
• `` -> `...66`
• `` -> `...67`
• `` -> `...68`
• `` -> `...69`
• `` -> `...70`
• `` -> `...71`
• `` -> `...72`
• `` -> `...73`
• `` -> `...74`
• `` -> `...75`
• `` -> `...76`
• `` -> `...77`
• `` -> `...78`
• `` -> `...79`
• `` -> `...80`
• `` -> `...81`
• `` -> `...82`
• `` -> `...83`
• `` -> `...84`
• `` -> `...85`
• `` -> `...86`
• `` -> `...87`
• `` -> `...88`
• `` -> `...89`
• `` -> `...90`
• `` -> `...91`
• `` -> `...92`
• `` -> `...93`
• `` -> `...94`
• `` -> `...95`
• `` -> `...96`
• `` -> `...97`
• `` -> `...98`
• `` -> `...99`
• `` -> `...100`
• `` -> `...101`
• `` -> `...102`
• `` -> `...103`
• `` -> `...104`
• `` -> `...105`
• `` -> `...106`
• `` -> `...107`
• `` -> `...108`
• `` -> `...109`
• `` -> `...110`
• `` -> `...111`
• `` -> `...112`
• `` -> `...113`
• `` -> `...114`
• `` -> `...115`
• `` -> `...116`
• `` -> `...117`
• `` -> `...118`
• `` -> `...119`
• `` -> `...120`
• `` -> `...121`
• `` -> `...122`
• `` -> `...123`
• `` -> `...124`
• `` -> `...125`
• `` -> `...126`
• `` -> `...127`
• `` -> `...128`
• `` -> `...129`
• `` -> `...130`
• `` -> `...131`
• `` -> `...132`
• `` -> `...133`
• `` -> `...134`
• `` -> `...135`
• `` -> `...136`
• `` -> `...137`
• `` -> `...138`
• `` -> `...139`
• `` -> `...140`
• `` -> `...141`
• `` -> `...142`
• `` -> `...143`
• `` -> `...144`
• `` -> `...145`
• `` -> `...146`
• `` -> `...147`
• `` -> `...148`
• `` -> `...149`
• `` -> `...150`
• `` -> `...151`
• `` -> `...152`
• `` -> `...153`
• `` -> `...154`
• `` -> `...155`
• `` -> `...156`
• `` -> `...157`
• `` -> `...158`
• `` -> `...159`
• `` -> `...160`
• `` -> `...161`
• `` -> `...162`
• `` -> `...163`
• `` -> `...164`
• `` -> `...165`
• `` -> `...166`
• `` -> `...167`
• `` -> `...168`
• `` -> `...169`
• `` -> `...170`
• `` -> `...171`
• `` -> `...172`
• `` -> `...173`
• `` -> `...174`
• `` -> `...175`
• `` -> `...176`
• `` -> `...177`
• `` -> `...178`
• `` -> `...179`
• `` -> `...180`
• `` -> `...181`
• `` -> `...182`
• `` -> `...183`
• `` -> `...184`
• `` -> `...185`
• `` -> `...186`
• `` -> `...187`
• `` -> `...188`
• `` -> `...189`
• `` -> `...190`
• `` -> `...191`
• `` -> `...192`
• `` -> `...193`
• `` -> `...194`
• `` -> `...195`
• `` -> `...196`
• `` -> `...197`
• `` -> `...198`
• `` -> `...199`
• `` -> `...200`
• `` -> `...201`
• `` -> `...202`
• `` -> `...203`
• `` -> `...204`
• `` -> `...205`
• `` -> `...206`
• `` -> `...207`
• `` -> `...208`
• `` -> `...209`
• `` -> `...210`
• `` -> `...211`
• `` -> `...212`
• `` -> `...213`
• `` -> `...214`
• `` -> `...215`
• `` -> `...216`
• `` -> `...217`
• `` -> `...218`
• `` -> `...219`
• `` -> `...220`
• `` -> `...221`
• `` -> `...222`
• `` -> `...223`
• `` -> `...224`
• `` -> `...225`
• `` -> `...226`
• `` -> `...227`
• `` -> `...228`
• `` -> `...229`
• `` -> `...230`
• `` -> `...231`
• `` -> `...232`
• `` -> `...233`
• `` -> `...234`
• `` -> `...235`
• `` -> `...236`
• `` -> `...237`
• `` -> `...238`
• `` -> `...239`
• `` -> `...240`
• `` -> `...241`
• `` -> `...242`
• `` -> `...243`
• `` -> `...244`
• `` -> `...245`
• `` -> `...246`
• `` -> `...247`
• `` -> `...248`
• `` -> `...249`
• `` -> `...250`
• `` -> `...251`
• `` -> `...252`
• `` -> `...253`
• `` -> `...254`
• `` -> `...255`
• `` -> `...256`
Rows: 1158 Columns: 256
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (6): LOCATION, INDICATOR, SUBJECT, MEASURE, FREQUENCY, Flag Codes
dbl   (2): TIME, Value
lgl (248): ...9, ...10, ...11, ...12, ...13, ...14, ...15, ...16, ...17, ......

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

     LOCATION INDICATOR SUBJECT MEASURE FREQUENCY TIME Value     Flag Codes
1    AUS      HUR       TOT     PC_LF   A         1990  6.923000 NA
2    AUS      HUR       TOT     PC_LF   A         1991  9.576522 NA
3    AUS      HUR       TOT     PC_LF   A         1992 10.728140 NA
⋮    ⋮        ⋮         ⋮       ⋮       ⋮         ⋮    ⋮         ⋮
1156 CRI      HUR       TOT     PC_LF   A         2019 11.75539  NA
1157 CRI      HUR       TOT     PC_LF   A         2020 19.60688  NA
1158 CRI      HUR       TOT     PC_LF   A         2021 16.43337  NA
     ...9 ...10 ⋯ ...247 ...248 ...249 ...250 ...251 ...252 ...253 ...254
1    NA   NA    ⋯ NA     NA     NA     NA     NA     NA     NA     NA
2    NA   NA    ⋯ NA     NA     NA     NA     NA     NA     NA     NA
3    NA   NA    ⋯ NA     NA     NA     NA     NA     NA     NA     NA
⋮    ⋮    ⋮     ⋱ ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮
1156 NA   NA    ⋯ NA     NA     NA     NA     NA     NA     NA     NA
1157 NA   NA    ⋯ NA     NA     NA     NA     NA     NA     NA     NA
1158 NA   NA    ⋯ NA     NA     NA     NA     NA     NA     NA     NA
     ...255 ...256
1    NA     NA
2    NA     NA
3    NA     NA
⋮    ⋮      ⋮
1156 NA     NA
1157 NA     NA
1158 NA     NA

In [53]:
income_portfolio_data <- read_csv("/home/jovyan/DSCI_100_125/income_portfolio.csv", skip = 1, col_names= c("year","X2","income_portfolio_return"))
income_portfolio_data

Rows: 598 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (8): year, X2, income_portfolio_return, X4, X5, X6, X7, X8
lgl (3): X9, X10, X11

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    year X2    income_portfolio_return X4         X5     X6     X7     X8
1   1997 1.70% 10.39%                  $11,038.80 30.99% -0.77% 9.44%  2.31%
2   1998 1.61% 11.30%                  $12,286.52 23.26% 15.60% 8.58%  10.59%
3   1999 2.68% 5.32%                   $12,939.61 23.81% 29.92% -0.76% 3.82%
⋮   ⋮    ⋮     ⋮                       ⋮          ⋮      ⋮      ⋮      ⋮
596 NA   NA    NA                      NA         NA     NA     NA     NA
597 NA   NA    NA                      NA         NA     NA     NA     NA
598 NA   NA    NA                      NA         NA     NA     NA     NA
    X9 X10 X11
1   NA NA  NA
2   NA NA  NA
3   NA NA  NA
⋮   ⋮  ⋮   ⋮
596 NA NA  NA
597 NA NA  NA
598 NA NA  NA

In [54]:
sixty_forty_and_forty_sixty_portfolio_data <- read_csv("/home/jovyan/DSCI_100_125/sixty_forty_and_forty_sixty_portfolio_data.csv", skip = 3, col_names= c("year","X2","60/40_portfolio_return","X3","40/60_portfolio_return"))
sixty_forty_and_forty_sixty_portfolio_data

Rows: 769 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (8): year, X2, 60/40_portfolio_return, X3, 40/60_portfolio_return, X6, X...
lgl (3): X9, X10, X11

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    year X2    60/40_portfolio_return X3         40/60_portfolio_return
1   1993 2.75% 10.25%                 $11,024.77 10.06%
2   1994 2.67% -1.16%                 $10,896.47 -1.66%
3   1995 2.54% 28.74%                 $14,028.51 25.22%
⋮   ⋮    ⋮     ⋮                      ⋮          ⋮
767 NA   NA    NA                     NA         NA
768 NA   NA    NA                     NA         NA
769 NA   NA    NA                     NA         NA
    X6         X7     X8     X9 X10 X11
1   $11,005.93 10.62% 9.68%  NA NA  NA
2   $10,823.09 -0.17% -2.66% NA NA  NA
3   $13,552.99 35.79% 18.18% NA NA  NA
⋮   ⋮          ⋮      ⋮      ⋮  ⋮   ⋮
767 NA         NA     NA     NA NA  NA
768 NA         NA     NA     NA NA  NA
769 NA         NA     NA     NA NA  NA

In [55]:
growth_moderate_conservative_portfolios_data <- read_csv("/home/jovyan/DSCI_100_125/growth_moderate_conservative_portfolios.csv", skip = 3, col_names= c("year","X2","growth_portfolio_return","X3","moderate_portfolio_return","X4","conservative_portfolio_return"))
growth_moderate_conservative_portfolios_data

Rows: 782 Columns: 16
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (12): year, X2, growth_portfolio_return, X3, moderate_portfolio_return, ...
lgl  (4): X13, X14, X15, X16

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    year X2    growth_portfolio_return X3         moderate_portfolio_return
1   1997 1.70% 17.50%                  $11,750.34 15.13%
2   1998 1.61% 18.26%                  $13,896.28 15.94%
3   1999 2.68% 20.79%                  $16,785.54 15.63%
⋮   ⋮    ⋮     ⋮                       ⋮          ⋮
780 NA   NA    NA                      NA         NA
781 NA   NA    NA                      NA         NA
782 NA   NA    NA                      NA         NA
    X4         conservative_portfolio_return X8         X9     X10    X11
1   $11,513.16 12.76%                        $11,275.98 30.99% -0.77% 9.44%
2   $13,348.69 13.62%                        $12,812.10 23.26% 15.60% 8.58%
3   $15,435.47 10.47%                        $14,154.06 23.81% 29.92% -0.76%
⋮   ⋮          ⋮                             ⋮          ⋮      ⋮      ⋮
780 NA         NA                            NA         NA     NA     NA
781 NA         NA                            NA         NA     NA     NA
782 NA         NA                            NA         NA     NA     NA
    X12    X13 X14 X15 X16
1   2.31%  NA  NA  NA  NA
2   10.59% NA  NA  NA  NA
3   3.82%  NA  NA  NA  NA
⋮   ⋮      ⋮   ⋮   ⋮   ⋮
780 NA     NA  NA  NA  NA
781 NA     NA  NA  NA  NA
782 NA     NA  NA  NA  NA