New Data Sets

In [1]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [17]:
unemp_url <- "https://raw.githubusercontent.com/Arioniums/DSCI_100_125/main/Unemployment_Data_since_1987.csv"
unemp_path <- "Unemployment_Data_since_1987.csv"
download.file(unemp_url, destfile = unemp_path)
unemp_data <- read_csv(unemp_path)

#filtering for USA unemployment data, selecting for TIME and Value columns, and then filtering years to only 1997-2021
unemployment_data <- filter(unemp_data, LOCATION == "USA") |>
                    select(TIME, Value) |>
                    filter(between(TIME, 1987, 2021))

##renaming TIME column into year and Value column into annual_unemployment rate
names(unemployment_data)[names(unemployment_data) == 'TIME'] <- 'Year'
names(unemployment_data)[names(unemployment_data) == 'Value'] <- 'unemployment_rate_percentage'

unemployment_data

Rows: 1216 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (6): LOCATION, INDICATOR, SUBJECT, MEASURE, FREQUENCY, Flag Codes
dbl (2): TIME, Value

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

   Year unemployment_rate_percentage
1  1987 6.191667
2  1988 5.491667
3  1989 5.266667
4  1990 5.616667
5  1991 6.816667
6  1992 7.508333
7  1993 6.900000
8  1994 6.083333
9  1995 5.608333
10 1996 5.416667
11 1997 4.950000
12 1998 4.508333
13 1999 4.216667
14 2000 3.991667
15 2001 4.733333
16 2002 5.775000
17 2003 5.991667
18 2004 5.533333
19 2005 5.066667
20 2006 4.616667
21 2007 4.616667
22 2008 5.775000
23 2009 9.266666
24 2010 9.616667
25 2011 8.950000
26 2012 8.066667
27 2013 7.375000
28 2014 6.166667
29 2015 5.291667
30 2016 4.866667
31 2017 4.350000
32 2018 3.900000
33 2019 3.666667
34 2020 8.091666
35 2021 5.366667

In [18]:
#importing gdp growth rate data
gdp_url <- "https://raw.githubusercontent.com/Arioniums/DSCI_100_125/main/US_GDP_Growth.csv"
gdp_path <- "US_GDP_Growth.csv"
download.file(gdp_url, destfile = gdp_path)
g_data <- read_csv(gdp_path)

#reformatting the year values and filtering years to only 1997-2021
gdp_data <- select(g_data, Year, "GDP growth (annual %)") |>
                filter(between(Year, 1987, 2021))

#clarification of gdp growth rate unit (percentage)
names(gdp_data)[names(gdp_data) == 'GDP growth (annual %)'] <- 'gdp_growth_rate_percentage'

gdp_data

New names:
• `` -> `...3`
• `` -> `...4`
• `` -> `...5`
• `` -> `...6`
• `` -> `...7`
• `` -> `...8`
• `` -> `...9`
• `` -> `...10`
• `` -> `...11`
• `` -> `...12`
• `` -> `...13`
Rows: 35 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl  (2): Year, GDP growth (annual %)
lgl (11): ...3, ...4, ...5, ...6, ...7, ...8, ...9, ...10, ...11, ...12, ...13

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

   Year gdp_growth_rate_percentage
1  1987  3.4592520
2  1988  4.1770613
3  1989  3.6726482
4  1990  1.8859650
5  1991 -0.1082648
6  1992  3.5224405
7  1993  2.7517811
8  1994  4.0287933
9  1995  2.6842173
10 1996  3.7725655
11 1997  4.4471749
12 1998  4.4813944
13 1999  4.7944990
14 2000  4.0771595
15 2001  0.9543387
16 2002  1.6959429
17 2003  2.7962091
18 2004  3.8525526
19 2005  3.4832203
20 2006  2.7828106
21 2007  2.0105076
22 2008  0.1221884
23 2009 -2.5998884
24 2010  2.7088567
25 2011  1.5498950
26 2012  2.2806876
27 2013  1.8418754
28 2014  2.2877759
29 2015  2.7063696
30 2016  1.6674721
31 2017  2.2556805
32 2018  2.9188569
33 2019  2.2888699
34 2020 -3.4045897
35 2021  5.6711072

In [ ]:
#importing sixty/forty and forty/sixty portfolio data
portfolio_url <- "https://raw.githubusercontent.com/Arioniums/DSCI_100_125/main/Annual_Portfolio_Returns_and_Inflation_data.csv"                                          
portfolio_path <- "Annual_Portfolio_Returns_and_Inflation_data.csv"
download.file(portfolio_url, destfile = portfolio_path)

#selecting for year, 60/40_portfolio_return, 40/60_portfolio_return, and filtering years to only 1997-2021
portfolio_data_c <- read_csv(portfolio_path, col_names= c("Year", "Inflation","Bogleheads Three Fun", "60/40_portfolio_return","X3","40/60_portfolio_return")) |>
                                                select("Year", "Inflation", "Bogleheads Three Fun", "60/40 Portfolio", "40/60 Portfolio", "Harry Brown Permanent Portfolio", "Gold") |>
                                                filter(between(year, 1997, 2021))

#deleting the percentage unit in the column 60/40_portfolio_return and renaming the 60/40_portfolio_return into 60/40_portfolio_return_percentage
sf_fs_portfolio_data_c$'60/40_portfolio_return' = as.numeric(gsub("[\\%,]", "", sf_fs_portfolio_data_c$'60/40_portfolio_return'))
names(sf_fs_portfolio_data_c)[names(sf_fs_portfolio_data_c) == '60/40_portfolio_return'] <- '60/40_portfolio_return_percentage'

#deleting the percentage unit in the column 40/60_portfolio_return and renaming the 40/60_portfolio_return into 40/60_portfolio_return_percentage
sf_fs_portfolio_data_c$'40/60_portfolio_return' = as.numeric(gsub("[\\%,]", "", sf_fs_portfolio_data_c$'40/60_portfolio_return'))
names(sf_fs_portfolio_data_c)[names(sf_fs_portfolio_data_c) == '40/60_portfolio_return'] <- '40/60_portfolio_return_percentage'

#c stands for cleaned
sf_fs_portfolio_data_c